### ISSUE TITLE
Missmatch Component and Controller

### ISSUE THREAD

**Issue by dukeval** [Chaos-Tech-Corp/Input-Field-Lookup#1]
Hi, thank you for posting this code.  I'm working on implementing a search feature in my lightning component and getting a few errors.  It appears that the code for the controller doesn't match that of the component.  In the component you're calling an event for onBlur and onFocus but those functions aren't available in the controller.  Also, I don't see where you are providing a way to do the actual search.  Is there a way you can provide the implementation?

**Comment by jachaos** [comment]
Hello,

thanks for pointing it out, I made I mistake on the last commit and I mixed different files.
I reviewed the component to make sure the right code has been placed in the right files.
You should be able to see how everything works now.
