### ISSUE TITLE
Error in Lightning Component

### ISSUE THREAD

**Issue by elihaugen** [Chaos-Tech-Corp/Input-Field-Lookup#2]
I get this error when I try to save the lightning component. Any idea why? 

Failed to save lookupField.cmp: No EVENT named markup://c:selectedsObjectRecordEvent found : [markup://c:lookupField]: Source

**Comment by jachaos** [comment]
Hello,
Thanks for notice, it looks like I forgot to include one file for the vent. I added it now and update the installation details as well as the deploy2.org link.
Please let me know if encounter any other issues.

**Comment by elihaugen** [comment]
Looks like that worked. Thank you!
