### ISSUE TITLE
How to Use on Site

### ISSUE THREAD

**Issue by prachi98arya** [Chaos-Tech-Corp/Input-Field-Lookup#4]
I am having a custom vf page for self registration in community. And I am embedding this component in my vf page. The results for searching any account by name are not appearing in the lookup component when testing on site where as it is working in the local preview of vf page. Can you help me resolve this issue?

**Comment by jachaos** [comment]
I don't know much about VF, but might be a permission issue. Have you checked if you have access to the records from an unathorized (before login) page?

**Comment by jachaos** [comment]
No answer in 27 days, closing the issue as I am not able to replicate it.
